name: Check Specific File Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-specific-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for Changes in helm/crd/all.yaml
        id: check_changes
        run: |
          ls
          if git diff --name-only | grep -q "^helm/crd/all.yaml$"; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Print Message
        if: env.changes == 'true'
        run: echo "echooo"
