name: Check Specific File Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CHANGED: false

jobs:
  check-specific-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Source Branch Name
        id: get_source_branch
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            # For PR event, we can directly use the source branch
            echo "SOURCE_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          elif [[ $GITHUB_EVENT_NAME == "push" ]]; then
            # For push event (merge), get the merge commit and extract the source branch
            # Find the merge commit hash
            MERGE_COMMIT=$(git log -1 --merges --pretty=%H)
            # Extract the source branch from the merge commit message
            SOURCE_BRANCH=$(git show -s --pretty=%B $MERGE_COMMIT | grep -oP '(?<=from )\S+')
            echo "SOURCE_BRANCH=${SOURCE_BRANCH}" >> $GITHUB_ENV
          fi
          echo "Source branch is: $SOURCE_BRANCH"

      - name: Check for Changes in helm/crd/all.yaml
        id: check_changes
        run: |
          echo "Checking for changes between ${{ env.SOURCE_BRANCH }} and master"
          git fetch origin master
          if git diff --name-only origin/${{ env.SOURCE_BRANCH }}..master | grep -q "helm/crd/all.yaml"; then
            echo "File helm/crd/all.yaml was changed."
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in helm/crd/all.yaml."
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Print Message
        if: env.CHANGED == 'true'
        run: |
          echo "Changes detected in helm/crd/all.yaml"
          echo "${{ env.CHANGED }}"
