name: Check Specific File Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CHANGED: false
jobs:
  check-specific-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Changes in helm/crd/all.yaml
        id: check_changes
        run: |
          git fetch origin master
          if git --no-pager log -n 1 --name-only --pretty=format: | grep -q "helm/crd/all.yaml"; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

  process-changes:
    needs: check-specific-file
    runs-on: ubuntu-latest
    if: needs.check-specific-file.outputs.CHANGED == 'true'
    steps:
      - name: Checkout other repository
        uses: actions/checkout@v4
        with: 
          repository: olamilekan000/leased-based-le
          token: ${{ secrets.PAT }}

      - name: Create and checkout new branch
        run: |
          SHORT_UID=$(uuidgen | cut -c1-8)
          echo "SHORT_UID=$SHORT_UID" >> $GITHUB_ENV
          git checkout -b file-changed-${{ env.TAG }}-$SHORT_UID

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "add new change to file version ${{ env.TAG }}-${{ env.SHORT_UID }}"
          git push origin file-changed-${{ env.TAG }}-${{ env.SHORT_UID }}

      - name: Create a pull request
        run: |
          gh pr create --base main --head file-changed-${{ env.TAG }}-${{ env.SHORT_UID }} \
            --title "Update Tyk Operator CRD for version file-changed-${{ env.TAG }}-${{ env.SHORT_UID }}" \
            --body "Changes include CRD updates from Tyk Operator for file-changed-${{ env.TAG }}-${{ env.SHORT_UID }}."
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
